#!/bin/bash
for i in{1..10}; do
    password=$(mysql -u -root -p'root' -e "USE USER_BD, SELECT password FROM USERS where id=$i;")
echo $password

temp_pw=$(echo $password | openssl enc -aes-256-cbc -md sh512 -a -pbkdf2 -iter 10000 -salt -pass pass:Secret@123#) //sozdaem peremennuu v kotoruu zapisivaem zashifrovannoe znachenie passworda

mysql -u root -p'root' -e "USE USER_DB1; UPDATE USERS SET password = '$temp_pw' WHERE id='$i';"
done


// enc == komanda zashifrovivaniya
//-aes-256-cbc == algorithm shifrovaniya
//-md sh512 == sozdaem hash zashifrovannogo parolya
//-a == vkluchaet kodirovanie v base64
//-pbkdf2 == psevdorandomnaya funkciya dlya extra zashiti parolya putem HMAC
//iter 10000 == kol-vo iteraciy
//-salt == random data fed as an additional input to a one-way function that hashes password
//-pass pass:Secret@123# == ispolzyet dannii parol shifrovaniya
